In [ ]:
!pip install opendatasets
import opendatasets as od

Requirement already satisfied: opendatasets in /usr/local/lib/python3.12/dist-packages (0.1.22)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from opendatasets) (4.67.1)
Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (from opendatasets) (1.7.4.5)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from opendatasets) (8.3.1)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (6.3.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2025.11.12)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (3.4.4)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (3.11)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (5.29.5)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (1.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (0.5.1)

In [ ]:
od.download("https://www.kaggle.com/datasets/vivovinco/2023-2024-nba-player-stats/data?select=2023-2024+NBA+Player+Stats+-+Regular.csv")

Skipping, found downloaded files in "./2023-2024-nba-player-stats" (use force=True to force download)

In [ ]:
import os

os.listdir("/content/2023-2024-nba-player-stats")

['2023-2024 NBA Player Stats - Playoffs.csv',
 '2023-2024 NBA Player Stats - Regular.csv']

In [ ]:
import pandas as pd

data = pd.read_csv("/content/2023-2024-nba-player-stats/2023-2024 NBA Player Stats - Regular.csv", encoding="latin1", sep=";")
data.head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Precious Achiuwa,PF-C,24,TOT,74,18,21.9,3.2,6.3,...,0.616,2.6,4.0,6.6,1.3,0.6,0.9,1.1,1.9,7.6
1,1,Precious Achiuwa,C,24,TOR,25,0,17.5,3.1,6.8,...,0.571,2.0,3.4,5.4,1.8,0.6,0.5,1.2,1.6,7.7
2,1,Precious Achiuwa,PF,24,NYK,49,18,24.2,3.2,6.1,...,0.643,2.9,4.3,7.2,1.1,0.6,1.1,1.1,2.1,7.6
3,2,Bam Adebayo,C,26,MIA,71,71,34.0,7.5,14.3,...,0.755,2.2,8.1,10.4,3.9,1.1,0.9,2.3,2.2,19.3
4,3,Ochai Agbaji,SG,23,TOT,78,28,21.0,2.3,5.6,...,0.661,0.9,1.8,2.8,1.1,0.6,0.6,0.8,1.5,5.8

In [ ]:
unique_players = data.drop_duplicates(subset="Player", keep="first")
unique_players.head(20)

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Precious Achiuwa,PF-C,24,TOT,74,18,21.9,3.2,6.3,...,0.616,2.6,4.0,6.6,1.3,0.6,0.9,1.1,1.9,7.6
3,2,Bam Adebayo,C,26,MIA,71,71,34.0,7.5,14.3,...,0.755,2.2,8.1,10.4,3.9,1.1,0.9,2.3,2.2,19.3
4,3,Ochai Agbaji,SG,23,TOT,78,28,21.0,2.3,5.6,...,0.661,0.9,1.8,2.8,1.1,0.6,0.6,0.8,1.5,5.8
7,4,Santi Aldama,PF,23,MEM,61,35,26.5,4.0,9.3,...,0.621,1.2,4.6,5.8,2.3,0.7,0.9,1.1,1.5,10.7
8,5,Nickeil Alexander-Walker,SG,25,MIN,82,20,23.4,2.9,6.6,...,0.800,0.4,1.6,2.0,2.5,0.8,0.5,0.9,1.7,8.0
9,6,Grayson Allen,SG,28,PHO,75,74,33.5,4.5,9.1,...,0.878,0.6,3.3,3.9,3.0,0.9,0.6,1.3,2.1,13.5
10,7,Jarrett Allen,C,25,CLE,77,77,31.7,6.7,10.6,...,0.742,3.2,7.4,10.5,2.7,0.7,1.1,1.6,1.9,16.5
11,8,Timmy Allen,SF,24,MEM,5,0,25.0,1.2,4.6,...,0.500,0.8,2.6,3.4,1.0,0.8,0.0,0.4,3.6,2.6
12,9,Jose Alvarado,PG,25,NOP,56,0,18.4,2.5,6.2,...,0.673,0.4,1.8,2.3,2.1,1.1,0.3,0.7,1.6,7.1
13,10,Kyle Anderson,PF,30,MIN,79,10,22.6,2.5,5.5,...,0.708,0.8,2.7,3.5,4.2,0.9,0.6,1.2,1.6,6.4
14,11,Giannis Antetokounmpo,PF,29,MIL,73,73,35.2,11.5,18.8,...,0.657,2.7,8.8,11.5,6.5,1.2,1.1,3.4,2.9,30.4
15,12,Thanasis Antetokounmpo,PF,31,MIL,34,0,4.6,0.5,0.9,...,0.000,0.2,0.2,0.4,0.5,0.2,0.1,0.4,0.7,0.9
16,13,Cole Anthony,PG,23,ORL,81,0,22.4,4.1,9.4,...,0.826,0.8,3.0,3.8,2.9,0.8,0.5,1.6,2.2,11.6
17,14,OG Anunoby,SF,26,TOT,50,50,34.0,5.6,11.5,...,0.753,0.9,3.2,4.2,2.1,1.4,0.7,1.6,2.4,14.7
20,15,Ryan Arcidiacono,PG,29,NYK,20,0,2.3,0.0,0.3,...,0.000,0.0,0.4,0.4,0.2,0.1,0.0,0.1,0.3,0.0
21,16,Deni Avdija,SF,23,WAS,75,75,30.1,5.4,10.7,...,0.740,1.1,6.1,7.2,3.8,0.8,0.5,2.1,2.5,14.7
22,17,Deandre Ayton,C,25,POR,55,55,32.4,7.8,13.6,...,0.823,3.2,7.9,11.1,1.6,1.0,0.8,1.8,2.0,16.7
23,18,Udoka Azubuike,C,24,PHO,16,0,7.1,1.0,1.4,...,0.231,0.7,1.3,2.0,0.2,0.1,0.4,0.3,1.1,2.2
24,19,Ibou Badji,C,21,POR,22,1,10.3,0.6,1.0,...,0.500,0.9,1.4,2.3,0.6,0.1,0.9,0.7,2.1,1.5
25,20,Marvin Bagley III,C,24,TOT,50,25,21.1,4.8,8.2,...,0.762,2.6,3.6,6.2,1.1,0.4,0.7,1.2,1.6,11.7

In [ ]:
player_names = data["Player"].unique().tolist()
player_names

['Precious Achiuwa',
 'Bam Adebayo',
 'Ochai Agbaji',
 'Santi Aldama',
 'Nickeil Alexander-Walker',
 'Grayson Allen',
 'Jarrett Allen',
 'Timmy Allen',
 'Jose Alvarado',
 'Kyle Anderson',
 'Giannis Antetokounmpo',
 'Thanasis Antetokounmpo',
 'Cole Anthony',
 'OG Anunoby',
 'Ryan Arcidiacono',
 'Deni Avdija',
 'Deandre Ayton',
 'Udoka Azubuike',
 'Ibou Badji',
 'Marvin Bagley III',
 'Amari Bailey',
 'Patrick Baldwin Jr.',
 'LaMelo Ball',
 'Mo Bamba',
 'Paolo Banchero',
 'Desmond Bane',
 'Dalano Banton',
 'Dominick Barlow',
 'Harrison Barnes',
 'Scottie Barnes',
 'RJ Barrett',
 'Charles Bassey',
 'Emoni Bates',
 'Keita Bates-Diop',
 'Nicolas Batum',
 'Darius Bazley',
 'Bradley Beal',
 'Malik Beasley',
 'MarJon Beauchamp',
 'Jules Bernard',
 'D?vis Bert?ns',
 'Patrick Beverley',
 'Saddiq Bey',
 'Goga Bitadze',
 'Onuralp Bitim',
 'Bismack Biyombo',
 'Anthony Black',
 'Leaky Black',
 'Buddy Boeheim',
 'Bogdan Bogdanovi?',
 'Bojan Bogdanovi?',
 'Bol Bol',
 'Marques Bolden',
 'Devin Booker',
 'Brandon Boston Jr.',
 'Chris Boucher',
 'James Bouknight',
 'Jamaree Bouyea',
 'Malaki Branham',
 'Christian Braun',
 'Mikal Bridges',
 'Miles Bridges',
 'Oshae Brissett',
 'Izaiah Brockington',
 'Malcolm Brogdon',
 'Armoni Brooks',
 'Dillon Brooks',
 'Bruce Brown',
 'Charlie Brown Jr.',
 'Greg Brown III',
 'Jaylen Brown',
 'Kendall Brown',
 'Kobe Brown',
 'Moses Brown',
 'Troy Brown Jr.',
 'Jalen Brunson',
 'Thomas Bryant',
 'Kobe Bufkin',
 'Reggie Bullock',
 'Alec Burks',
 'Jared Butler',
 'Jimmy Butler',
 'Jamal Cain',
 'Kentavious Caldwell-Pope',
 'Toumani Camara',
 'Clint Capela',
 'Jevon Carter',
 'Wendell Carter Jr.',
 'D.J. Carton',
 'Alex Caruso',
 'Colin Castleton',
 'Malcolm Cazalon',
 'Julian Champagnie',
 'Justin Champagnie',
 'Max Christie',
 'Sidy Cissoko',
 'Brandon Clarke',
 'Jordan Clarkson',
 'Nic Claxton',
 'Noah Clowney',
 'Amir Coffey',
 'John Collins',
 'Zach Collins',
 'Mike Conley',
 'Pat Connaughton',
 'Bilal Coulibaly',
 'Ricky Council IV',
 'Robert Covington',
 'Torrey Craig',
 'Jae Crowder',
 'Jalen Crutcher',
 'Cade Cunningham',
 'Seth Curry',
 'Stephen Curry',
 'Dyson Daniels',
 'Anthony Davis',
 'Johnny Davis',
 'JD Davison',
 'Dexter Dennis',
 'DeMar DeRozan',
 'Moussa Diabaté',
 'Mamadi Diakite',
 'Hamidou Diallo',
 'Gradey Dick',
 'Ousmane Dieng',
 'Spencer Dinwiddie',
 'Donte DiVincenzo',
 'Luka Don?i?',
 'Luguentz Dort',
 'Ayo Dosunmu',
 'Jeff Dowtin',
 'Henri Drell',
 'Andre Drummond',
 'Chris Duarte',
 'David Duke Jr.',
 'Kris Dunn',
 'Kevin Durant',
 'Jalen Duren',
 'Tari Eason',
 'Anthony Edwards',
 'Kessler Edwards',
 'Keon Ellis',
 'Joel Embiid',
 'Drew Eubanks',
 'Tosan Evbuomwan',
 'Dante Exum',
 'Bruno Fernando',
 'Dorian Finney-Smith',
 'Adam Flagler',
 'Malachi Flynn',
 'Simone Fontecchio',
 'Jordan Ford',
 'Trent Forrest',
 'Evan Fournier',
 "De'Aaron Fox",
 'Javon Freeman-Liberty',
 'Alex Fudge',
 'Markelle Fultz',
 'Andrew Funk',
 'Wenyen Gabriel',
 'Daniel Gafford',
 'Danilo Gallinari',
 'Darius Garland',
 'Usman Garuba',
 'Luka Garza',
 'Kaiser Gates',
 'Keyonte George',
 'Paul George',
 'Taj Gibson',
 'Josh Giddey',
 'Harry Giles',
 'Shai Gilgeous-Alexander',
 'Anthony Gill',
 'Collin Gillespie',
 'Jacob Gilyard',
 'Rudy Gobert',
 'Jordan Goodwin',
 'Aaron Gordon',
 'Eric Gordon',
 "Devonte' Graham",
 'Jerami Grant',
 'RaiQuan Gray',
 'A.J. Green',
 'Danny Green',
 'Draymond Green',
 'Jalen Green',
 'Javonte Green',
 'Jeff Green',
 'Josh Green',
 'AJ Griffin',
 'Quentin Grimes',
 'Mouhamadou Gueye',
 'Mouhamed Gueye',
 'Rui Hachimura',
 'Ashton Hagans',
 'Tyrese Haliburton',
 'R.J. Hampton',
 'Tim Hardaway Jr.',
 'James Harden',
 'Jaden Hardy',
 'Ron Harper Jr.',
 'Gary Harris',
 'Joe Harris',
 'Kevon Harris',
 'Tobias Harris',
 'Shaquille Harrison',
 'Josh Hart',
 'Isaiah Hartenstein',
 'Sam Hauser',
 'Jordan Hawkins',
 'Jaxson Hayes',
 'Killian Hayes',
 'Gordon Hayward',
 'Scoot Henderson',
 'Taylor Hendricks',
 'Tyler Herro',
 'Buddy Hield',
 'Haywood Highsmith',
 'Nate Hinton',
 "D'Moi Hodge",
 'Aaron Holiday',
 'Jrue Holiday',
 'Justin Holiday',
 'Richaun Holmes',
 'Chet Holmgren',
 'Jalen Hood-Schifino',
 'Al Horford',
 'Talen Horton-Tucker',
 'Danuel House Jr.',
 'Caleb Houstan',
 'Jett Howard',
 'Kevin Huerter',
 'Jay Huff',
 "De'Andre Hunter",
 'Matthew Hurt',
 'Bones Hyland',
 'Joe Ingles',
 'Brandon Ingram',
 'Kyrie Irving',
 'Jonathan Isaac',
 'Jaden Ivey',
 'Andre Jackson Jr.',
 'GG Jackson II',
 'Isaiah Jackson',
 'Jaren Jackson Jr.',
 'Justin Jackson',
 'Quenton Jackson',
 'Reggie Jackson',
 'Trayce Jackson-Davis',
 'LeBron James',
 'Jaime Jaquez Jr.',
 'DeJon Jarreau',
 'DaQuan Jeffries',
 'Trey Jemison',
 'Ty Jerome',
 'Isaiah Joe',
 'Cameron Johnson',
 'Jalen Johnson',
 'James Johnson',
 'Keldon Johnson',
 'Keon Johnson',
 'Keyontae Johnson',
 'Nikola Joki?',
 'Colby Jones',
 'Damian Jones',
 'Derrick Jones Jr.',
 'Herbert Jones',
 'Mason Jones',
 'Tre Jones',
 'Tyus Jones',
 'DeAndre Jordan',
 'Cory Joseph',
 'Nikola Jovi?',
 'Johnny Juzang',
 'Luke Kennard',
 'Walker Kessler',
 'Braxton Key',
 'Corey Kispert',
 'Maxi Kleber',
 'Kevin Knox',
 'John Konchar',
 'Furkan Korkmaz',
 'Luke Kornet',
 'Vit Krejci',
 'Jonathan Kuminga',
 'Kyle Kuzma',
 'Jock Landale',
 'Jake LaRavia',
 'Zach LaVine',
 'A.J. Lawson',
 'Saben Lee',
 'Alex Len',
 'Kawhi Leonard',
 'Caris LeVert',
 'Kira Lewis Jr.',
 'Maxwell Lewis',
 'E.J. Liddell',
 'Damian Lillard',
 'Nassir Little',
 'Dereck Lively II',
 'Isaiah Livers',
 'Chris Livingston',
 'Kenneth Lofton Jr.',
 'Kevon Looney',
 'Brook Lopez',
 'Robin Lopez',
 'Kevin Love',
 'Kyle Lowry',
 'Seth Lundy',
 'Trey Lyles',
 'Théo Maledon',
 'Sandro Mamukelashvili',
 'Terance Mann',
 'Tre Mann',
 'Boban Marjanovi?',
 'Lauri Markkanen',
 'Naji Marshall',
 'Caleb Martin',
 'Cody Martin',
 'KJ Martin',
 'Garrison Mathews',
 'Bennedict Mathurin',
 'Wesley Matthews',
 'Tyrese Maxey',
 'Skylar Mays',
 'Miles McBride',
 'CJ McCollum',
 'T.J. McConnell',
 'Jaden McDaniels',
 'Jalen McDaniels',
 'Doug McDermott',
 'JaVale McGee',
 'Bryce McGowens',
 'Jordan McLaughlin',
 "De'Anthony Melton",
 'Nathan Mensah',
 'Sam Merrill',
 'Chimezie Metu',
 'Vasilije Mici?',
 'Khris Middleton',
 'Brandon Miller',
 'Jordan Miller',
 'Leonard Miller',
 'Dariq Whitehead',
 'Patty Mills',
 'Shake Milton',
 'Justin Minaya',
 'Josh Minott',
 'Davion Mitchell',
 'Donovan Mitchell',
 'Evan Mobley',
 'Isaiah Mobley',
 'Malik Monk',
 'Moses Moody',
 'Xavier Moon',
 'Taze Moore',
 'Wendell Moore Jr.',
 'Ja Morant',
 'Marcus Morris',
 'Markieff Morris',
 'Monte Morris',
 'Trey Murphy III',
 'Dejounte Murray',
 'Jamal Murray',
 'Keegan Murray',
 'Kris Murray',
 'Mike Muscala',
 'Svi Mykhailiuk',
 'Larry Nance Jr.',
 'Pete Nance',
 'Andrew Nembhard',
 'Aaron Nesmith',
 'Georges Niang',
 'Daishen Nix',
 'Zeke Nnaji',
 'Jaylen Nowell',
 'Markquis Nowell',
 'Frank Ntilikina',
 'Jusuf Nurki?',
 'Jordan Nwora',
 "Royce O'Neale",
 'Chuma Okeke',
 'Josh Okogie',
 'Onyeka Okongwu',
 'Isaac Okoro',
 'Kelly Olynyk',
 'Eugene Omoruyi',
 'Cedi Osman',
 'Kelly Oubre Jr.',
 'Chris Paul',
 'Cameron Payne',
 'Gary Payton II',
 'Mãozinha Pereira',
 'Drew Peterson',
 'Filip Petru\x9aev',
 'Julian Phillips',
 'Jalen Pickett',
 'Scotty Pippen Jr.',
 'Mason Plumlee',
 'Brandin Podziemski',
 'Jakob Poeltl',
 'Aleksej Pokusevski',
 'Jordan Poole',
 'Craig Porter Jr.',
 'Jontay Porter',
 'Michael Porter Jr.',
 'Otto Porter Jr.',
 'Bobby Portis',
 'Kristaps Porzi??is',
 'Micah Potter',
 'Dwight Powell',
 'Norman Powell',
 'Jason Preston',
 'Joshua Primo',
 'Taurean Prince',
 'Payton Pritchard',
 'Olivier-Maxence Prosper',
 'Trevelin Queen',
 'Neemias Queta',
 'Immanuel Quickley',
 'Lester Quinones',
 "Jahmi'us Ramsey",
 'Julius Randle',
 'Duop Reath',
 'Austin Reaves',
 'Cam Reddish',
 'Paul Reed',
 'Naz Reid',
 'Jared Rhoden',
 'Nick Richards',
 'Josh Richardson',
 'Duncan Robinson',
 'Jerome Robinson',
 'Mitchell Robinson',
 'Orlando Robinson',
 'Jeremiah Robinson-Earl',
 'David Roddy',
 'Ryan Rollins',
 'Derrick Rose',
 'Terry Rozier',
 'Rayan Rupert',
 "D'Angelo Russell",
 'Matt Ryan',
 'Domantas Sabonis',
 'Luka \x8aamani?',
 'Jermaine Samuels',
 'Adama Sanogo',
 'Gui Santos',
 'Dario \x8aari?',
 'Olivier Sarr',
 'Marcus Sasser',
 'Admiral Schofield',
 'Dennis Schröder',
 'Dereon Seabron',
 'Alperen Sengun',
 'Brice Sensabaugh',
 'Collin Sexton',
 'Landry Shamet',
 "Day'Ron Sharpe",
 'Shaedon Sharpe',
 'Ben Sheppard',
 'Pascal Siakam',
 'Ben Simmons',
 'Kobi Simmons',
 'Anfernee Simons',
 'Zavier Simpson',
 'Jericho Sims',
 'Dmytro Skapintsev',
 'Jalen Slawson',
 'Javonte Smart',
 'Marcus Smart',
 'Dennis Smith Jr.',
 'Dru Smith',
 'Ish Smith',
 'Jabari Smith Jr.',
 'Jalen Smith',
 'Nick Smith Jr.',
 'Terquavion Smith',
 'Jeremy Sochan',
 'Pat Spencer',
 'Jaden Springer',
 'Lamar Stevens',
 'Isaiah Stewart',
 'Julian Strawther',
 'Max Strus',
 'Jalen Suggs',
 'Cole Swider',
 "Jae'Sean Tate",
 'Jayson Tatum',
 'Terry Taylor',
 'Garrett Temple',
 'Dalen Terry',
 'Daniel Theis',
 'Cam Thomas',
 'Isaiah Thomas',
 'Amen Thompson',
 'Ausar Thompson',
 'Klay Thompson',
 'Tristan Thompson',
 'JT Thor',
 'Matisse Thybulle',
 'Xavier Tillman Sr.',
 'Jacob Toppin',
 'Obi Toppin',
 'Juan Toscano-Anderson',
 'Karl-Anthony Towns',
 'Gary Trent Jr.',
 'Oscar Tshiebwe',
 'P.J. Tucker',
 'Myles Turner',
 'Hunter Tyson',
 'Stanley Umude',
 'Jonas Valan?i?nas',
 'Jarred Vanderbilt',
 'Fred VanVleet',
 'Devin Vassell',
 'Sasha Vezenkov',
 'Gabe Vincent',
 'Nikola Vu?evi?',
 'Tristan Vukcevic',
 'Dean Wade',
 'Franz Wagner',
 'Moritz Wagner',
 'Ish Wainright',
 'Jabari Walker',
 'Jarace Walker',
 'Lonnie Walker IV',
 'Cason Wallace',
 'Jordan Walsh',
 'T.J. Warren',
 'P.J. Washington',
 'TyTy Washington Jr.',
 'Yuta Watanabe',
 'Lindy Waters III',
 'Trendon Watford',
 'Peyton Watson',
 'Victor Wembanyama',
 'Blake Wesley',
 'Russell Westbrook',
 'Coby White',
 'Derrick White',
 'Jack White',
 'Cam Whitmore',
 'Aaron Wiggins',
 'Andrew Wiggins',
 'Lindell Wigginton',
 'Alondes Williams',
 'Brandon Williams',
 'Grant Williams',
 'Jalen Williams',
 'Jaylin Williams',
 'Jeenathan Williams',
 'Kenrich Williams',
 'Malik Williams',
 'Mark Williams',
 'Patrick Williams',
 'Robert Williams',
 'Vince Williams Jr.',
 'Ziaire Williams',
 'Zion Williamson',
 'D.J. Wilson',
 'Jalen Wilson',
 'Dylan Windler',
 'James Wiseman',
 'Isaiah Wong',
 'Christian Wood',
 'Delon Wright',
 'Thaddeus Young',
 'Trae Young',
 'Omer Yurtseven',
 'Cody Zeller',
 'Ivica Zubac']